import "./globals.css";
import { Delius } from "next/font/google";

const font = Delius({ subsets: ["latin"], weight: ['400'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
